# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  validate-code:
    desc: Make sure the code is clean
    cmds:
      - poetry run isort --check .
      - poetry run flake8 .
      - poetry run pytest --cov-report term-missing --cov=foo_cv tests/

  pypi-publish:
    desc: Build and publish the package to PyPI
    cmds:
      - poetry publish --build --username $FOO_CV_PYPI_USERNAME --password $FOO_CV_PYPI_PASSWORD

  build-LaTeX-image:
    cmds:
      - docker build -t latex -f LaTeX.Dockerfile .

  json-to-tex:
    cmds:
      - poetry run foo-cv cv_template.tex.jinja content.json foo.tex

  tex-to-pdf:
    cmds:
      - docker run -it --rm -v $PWD:/prj latex foo.tex

  clean:
    cmds:
      - rm -f foo.tex foo.aux foo.out foo.log texput.log

  build-cv:
    desc: Build the CV from foo.tex
    cmds:
      - task: json-to-tex
      - task: tex-to-pdf
      - task: clean
